### ISSUE TITLE
Exception with 1.0

### ISSUE THREAD

**Issue by rubengees** [santalu/aspect-ratio-imageview#1]
Version: `1.0`

I am getting this `Exception` and some similar ones when adding the dependency to my `build.gradle` and building (formatted for readability):

```java
{
  "kind": "error",
  "text": "No resource identifier found for attribute ari_aspect in package com.test.app",
  "sources": [{
    "file": "/home/my-project/app/src/main/res/layout/some_layout.xml",
    "position": {
      "startLine": 9
    }
  }],
  "original": "",
  "tool": "AAPT"
}
```

The latest commit on master works though, e.g. adding this to my `build.gradle`:

```groovy
compile 'com.github.santalu:aspect-ratio-imageview:86be53edf0'
```

I would prefer to use a stable release though, maybe create a `1.0.1`?

**Comment by santalu** [comment]
Hi, Thank you for using the library. I published 1.0.1 version.
